### ISSUE TITLE
Proposal: Motivation and Purpose

### ISSUE THREAD

**Issue by samson-bakos** [UBC-MDS/MacroView#6]

**Comment by J99thoms** [comment]
"In a few sentences, provide motivation for why you are creating a dashboard. Who is your target audience, and what role are you embodying? What problem could your dashboard solve for the intended user? You can read the [Project background section](https://pages.github.ubc.ca/MDS-2022-23/DSCI_532_viz-2_students/materials/assignments/milestone1.html#project-background) for some rough ideas. Be brief and clear."
