### ISSUE TITLE
Proposal: Research Questions/ Usage

### ISSUE THREAD

**Issue by samson-bakos** [UBC-MDS/MacroView#8]

**Comment by J99thoms** [comment]
"The purpose of this section is to get you to think about how your target audience might use the app you’re to designing and to account for those needs in the proposal.

For this, it can be helpful to create a [brief persona description](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/bring-on-contributors-using-personas-and-pathways/#personas) of a member in your intended target audience and write a small user story for what they might do with your app. User stories are typically written in a narrative style and include the specific context of usage, tasks associated with that use context, and a hypothetical walkthrough of how the user would accomplish those tasks with your app."

**Comment by ChesterAiGo** [comment]
Thanks for the description Jakob. Working on this now.

**Comment by ChesterAiGo** [comment]
Done. Please see pull request
